import type { Metadata } from "next";
import {   Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";


const Noto_Sans = Noto_Sans_JP({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:["400"]
});

const Noto_Sans2 = Noto_Sans_JP({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight:["400"]
});

export const metadata: Metadata = {
  title: "Book Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body
        className={`${Noto_Sans.variable} ${Noto_Sans2.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
